apiVersion: apps/v1
kind: Deployment
metadata:
  name: voicera-server
  namespace: voicera-server-backend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: voice-server
  template:
    metadata:
      labels:
        app: voice-server
    spec:
      nodeSelector:
        app: voicera
      containers:
        - name: voice-server
          image: registryharbor.bhashini.co.in/bhashini/voicera/v2v-server-prod
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7860
          resources:
            limits:
              cpu: "1"
              memory: "4Gi"
            requests:
              cpu: "200m"
              memory: "1Gi"
          envFrom:
            - secretRef:
                name: voicera-backend-secret
