apiVersion: v1
kind: Service
metadata:
  name: voicera-server
  namespace: voicera-server-backend
spec:
  selector:
    app: voice-server
  ports:
    - name: http
      port: 7860
      targetPort: 7860
