apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress/backend-ingress.yaml
  - ingress/server-ingress.yaml
  - ingress/frontend-ingress.yaml

patchesStrategicMerge:
  - patches/backend-deployment-patch.yaml
  - patches/server-deployment-patch.yaml
  - patches/frontend-deployment-patch.yaml
