apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voicera-frontend-ingress
  namespace: voicera-frontend
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx
  rules:
  - host: bhashini-voicera-main.bhashini.co.in
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: voicera-frontend
            port:
              number: 3000
