# STT Language Code Mappings
# Maps display names to provider-specific language codes.
# ElevenLabs Realtime STT: ISO 639-3 codes per ElevenLabs Speech-to-Text docs (Pipecat language_to_elevenlabs).

STT_LANGUAGE_MAP = {
    "Deepgram": {
        "Hindi": "hi",
        "English": "en-US",
        "English (India)": "en-IN",
        "English (United States)": "en-US",
        "Bengali": "bn",
        "Tamil": "ta",
        "Telugu": "te",
        "Gujarati": "gu",
        "Kannada": "kn",
        "Malayalam": "ml",
        "Marathi": "mr",
        "Punjabi": "pa",
        "Urdu": "ur",
    },
    "Google": {
        "Hindi": "hi-IN",
        "English": "en-US",
        "English (India)": "en-IN",
        "English (United States)": "en-US",
        "Bengali": "bn-IN",
        "Tamil": "ta-IN",
        "Telugu": "te-IN",
        "Gujarati": "gu-IN",
        "Kannada": "kn-IN",
        "Malayalam": "ml-IN",
        "Marathi": "mr-IN",
        "Punjabi": "pa-Guru-IN",
        "Odia": "or-IN",
        "Assamese": "as-IN",
        "Urdu": "ur-IN",
        "Nepali": "ne-NP",
        "Sanskrit": "sa-IN",
        "Bodo": "brx-IN",
        "Dogri": "doi-IN",
        "Konkani": "kok-IN",
        "Kashmiri": "ks-IN",
        "Maithili": "mai-IN",
        "Manipuri": "mni-IN",
        "Santali": "sat-IN",
        "Sindhi": "sd-IN",
    },
    "OpenAI": {
        "Hindi": "hi",
        "English": "en",
        "English (India)": "en",
        "English (United States)": "en",
        "Bengali": "bn",
        "Tamil": "ta",
        "Telugu": "te",
        "Gujarati": "gu",
        "Kannada": "kn",
        "Malayalam": "ml",
        "Marathi": "mr",
        "Punjabi": "pa",
        "Odia": "or",
        "Assamese": "as",
        "Urdu": "ur",
        "Nepali": "ne",
        "Sanskrit": "sa",
        "Bodo": "brx",
        "Dogri": "doi",
        "Konkani": "kok",
        "Kashmiri": "ks",
        "Maithili": "mai",
        "Manipuri": "mni",
        "Santali": "sat",
        "Sindhi": "sd",
    },
    "Sarvam": {
        "Hindi": "hi-IN",
        "English": "en-IN",
        "English (India)": "en-IN",
        "English (United States)": "en-US",
        "Bengali": "bn-IN",
        "Tamil": "ta-IN",
        "Telugu": "te-IN",
        "Gujarati": "gu-IN",
        "Kannada": "kn-IN",
        "Malayalam": "ml-IN",
        "Marathi": "mr-IN",
        "Punjabi": "pa-IN",
        "Odia": "od-IN",
        "Assamese": "as-IN",
        "Urdu": "ur-IN",
        "Nepali": "ne-IN",
        "Sanskrit": "sa-IN",
        "Bodo": "brx-IN",
        "Dogri": "doi-IN",
        "Konkani": "kok-IN",
        "Kashmiri": "ks-IN",
        "Maithili": "mai-IN",
        "Manipuri": "mni-IN",
        "Santali": "sat-IN",
        "Sindhi": "sd-IN",
    },
    "AI4Bharat": {
        "Hindi": "hi",
        "Bengali": "bn",
        "Bodo": "brx",
        "Dogri": "doi",
        "Tamil": "ta",
        "Telugu": "te",
        "Gujarati": "gu",
        "Kannada": "kn",
        "Konkani": "kok",
        "Kashmiri": "ks",
        "Maithili": "mai",
        "Malayalam": "ml",
        "Manipuri": "mni",
        "Marathi": "mr",
        "bhb": "bhb",
        "Punjabi": "pa",
        "Sanskrit": "sa",
        "Santali": "sat",
        "Sindhi": "sd",
        "Assamese": "as",
        "Odia": "or",
        "Nepali": "ne",
        "Urdu": "ur",
    },
    "ElevenLabs": {
        "English": "eng",
        "English (United States)": "eng",
        "English (India)": "eng",
        "Hindi": "hin",
        "Bengali": "ben",
        "Tamil": "tam",
        "Telugu": "tel",
        "Gujarati": "guj",
        "Kannada": "kan",
        "Malayalam": "mal",
        "Marathi": "mar",
        "Punjabi": "pan",
        "Odia": "ori",
        "Assamese": "asm",
        "Urdu": "urd",
        "Nepali": "nep",
        "Sindhi": "snd",
    },
    "Bhashini": {
        "Hindi": "hi",
        "Bengali": "bn",
        "Tamil": "ta",
        "Telugu": "te",
        "Gujarati": "gu",
        "Kannada": "kn",
        "Malayalam": "ml",
        "Marathi": "mr",
        "Punjabi": "pa",
        "Assamese": "as",
        "Odia": "or",
        "Nepali": "ne",
        "Bodo": "brx",
        "Dogri": "doi",
        "Kashmiri": "ks",
        "Konkani": "kok",
        "Maithili": "mai",
        "Manipuri": "mni",
        "Sanskrit": "sa",
        "Santali": "sat",
        "Sindhi": "sd",
        "Urdu": "ur",
    },
}
