# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import tts_pb2 as tts__pb2


class TTSServiceStub(object):
    """Client stub for the TTS gRPC service."""

    def __init__(self, channel):
        self.StreamTTS = channel.unary_stream(
            '/tts.TTSService/StreamTTS',
            request_serializer=tts__pb2.TTSRequest.SerializeToString,
            response_deserializer=tts__pb2.AudioChunk.FromString,
        )
        self.Health = channel.unary_unary(
            '/tts.TTSService/Health',
            request_serializer=tts__pb2.HealthRequest.SerializeToString,
            response_deserializer=tts__pb2.HealthResponse.FromString,
        )


class TTSServiceServicer(object):
    def StreamTTS(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TTSServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'StreamTTS': grpc.unary_stream_rpc_method_handler(
            servicer.StreamTTS,
            request_deserializer=tts__pb2.TTSRequest.FromString,
            response_serializer=tts__pb2.AudioChunk.SerializeToString,
        ),
        'Health': grpc.unary_unary_rpc_method_handler(
            servicer.Health,
            request_deserializer=tts__pb2.HealthRequest.FromString,
            response_serializer=tts__pb2.HealthResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'tts.TTSService', rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))

