# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tts.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ttts.proto\x12\x03tts\"Y\n\nTTSRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0f\n\x07speaker\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x17\n\x0fplay_steps_in_s\x18\x04 \x01(\x02\"A\n\nAudioChunk\x12\r\n\x05\x61udio\x18\x01 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x02 \x01(\r\x12\x0f\n\x07samples\x18\x03 \x01(\r\"\x0f\n\rHealthRequest\"[\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0e\n\x06\x64\x65vice\x18\x02 \x01(\t\x12\x13\n\x0bsample_rate\x18\x03 \x01(\r\x12\x14\n\x0cmodel_loaded\x18\x04 \x01(\x08\x32p\n\nTTSService\x12/\n\tStreamTTS\x12\x0f.tts.TTSRequest\x1a\x0f.tts.AudioChunk0\x01\x12\x31\n\x06Health\x12\x12.tts.HealthRequest\x1a\x13.tts.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tts_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals['_TTSREQUEST']._serialized_start = 18
    _globals['_TTSREQUEST']._serialized_end = 107
    _globals['_AUDIOCHUNK']._serialized_start = 109
    _globals['_AUDIOCHUNK']._serialized_end = 174
    _globals['_HEALTHREQUEST']._serialized_start = 176
    _globals['_HEALTHREQUEST']._serialized_end = 191
    _globals['_HEALTHRESPONSE']._serialized_start = 193
    _globals['_HEALTHRESPONSE']._serialized_end = 284
    _globals['_TTSSERVICE']._serialized_start = 286
    _globals['_TTSSERVICE']._serialized_end = 398

